#!/bin/sh
### BEGIN INIT INFO
# Provides:          usb_auto_off
# Required-Start:    $sysfsutils $keyboard_setup
# Required-Stop:     $sysfsutils
# Default-Start:     5
# Default-Stop:      
# Short-Description: Disable autoprobing of USB devices
# Description:       Disable autoprobing of USB devices
### END INIT INFO

# echo 0 | sudo tee /sys/bus/usb/drivers_autoprobe

case "$1" in
    start)
	echo 0 > /sys/bus/usb/drivers_autoprobe
	;;
    restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
    stop)
	echo 1 > /sys/bus/usb/drivers_autoprobe
	;;
    *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
